#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

USE_PROCD=1
START=99
STOP=9
PROCD_DEBUG=1
service_triggers()
{
        procd_add_interface_trigger "interface.*" "br-lan" /etc/init.d/mqtt reload
}
start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/mqtt.sh
	procd_append_param command -c /etc/mqtt/mqtt-client.conf
	procd_set_param pidfile /var/run/somefile.pid	
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
stop_service() {
	/usr/bin/mqtt.sh -s all
}
reload_service(){
	stop
	start
}
