#!/bin/sh
# /etc/init.d/mqtt
### BEGIN INIT INFO
# Provides:          mqtt
# Required-Start:    $network $remote_fs $syslog $all
# Required-Stop:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mqtt init script
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC=mqtt_client             # Introduce a short description here
NAME=mqtt             # Introduce the short server's name here
DAEMON=/usr/bin/mqtt.sh     # Introduce the server's location here
DAEMON_ARGS=""               # Arguments to run the daemon with
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
LOGFILE=/var/log/$NAME.log

# Exit if the package is not installed
[ -x $DAEMON ] || exit 0


# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh



case "$1" in
  start)

	$DAEMON -c  /etc/mqtt/mqtt-client.conf
  ;;
  stop)
	$DAEMON -s all
	;;
  status)
       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
       ;;
  restart|force-reload)
	$DAEMON -s all
	$DAEMON -c  /etc/mqtt/mqtt.conf
	;;
  *)
	echo "usage:mqtt start|stop|reload"
	;;
esac

:
